
import java.awt.Color;
import java.net.URL;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;





/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author dhion
 */
public class NewJFrame extends javax.swing.JFrame {
public boolean jogA = true;
    public boolean jogB = true;
    public boolean novaRodada = true;
    public boolean empate = false;
    public int pos = 0;
    public int i = 0, j = 0;
    public int rodada = 1;
    int op;
    public String linha1, linha2, linha3, coluna1, coluna2, coluna3, diagonal01, diagonal02;
    String[][] posVetor = new String[3][3];
    public Integer [][] resultado = new Integer[2][5];
    public int contClic = 0; 
    public int resultadoX = 0;
    public int resultadoy = 0;
    public int rX = 0;
    public int rY = 0;
    
    
     
     
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        
        initComponents();
        getContentPane().setBackground(Color.white);
        contador.setEnabled(false);
        contador.setText(Integer.toString(rodada));
         btnReiniciar.setEnabled(false);
         txtVisor.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botao1 = new javax.swing.JButton();
        botao2 = new javax.swing.JButton();
        botao3 = new javax.swing.JButton();
        botao4 = new javax.swing.JButton();
        botao5 = new javax.swing.JButton();
        botao6 = new javax.swing.JButton();
        botao7 = new javax.swing.JButton();
        botao8 = new javax.swing.JButton();
        botao9 = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();
        txtVisor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        contador = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(500, 600));
        setMinimumSize(new java.awt.Dimension(500, 600));
        getContentPane().setLayout(null);

        botao1.setFont(new java.awt.Font("Segoe UI", 3, 60)); // NOI18N
        botao1.setForeground(new java.awt.Color(255, 0, 0));
        botao1.setContentAreaFilled(false);
        botao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao1ActionPerformed(evt);
            }
        });
        getContentPane().add(botao1);
        botao1.setBounds(20, 17, 120, 60);

        botao2.setFont(new java.awt.Font("Segoe UI", 3, 60)); // NOI18N
        botao2.setForeground(new java.awt.Color(255, 0, 0));
        botao2.setContentAreaFilled(false);
        botao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao2ActionPerformed(evt);
            }
        });
        getContentPane().add(botao2);
        botao2.setBounds(150, 10, 160, 70);

        botao3.setFont(new java.awt.Font("Segoe UI", 3, 60)); // NOI18N
        botao3.setForeground(new java.awt.Color(255, 0, 0));
        botao3.setContentAreaFilled(false);
        botao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao3ActionPerformed(evt);
            }
        });
        getContentPane().add(botao3);
        botao3.setBounds(330, 17, 120, 60);

        botao4.setFont(new java.awt.Font("Segoe UI", 3, 60)); // NOI18N
        botao4.setForeground(new java.awt.Color(255, 0, 0));
        botao4.setContentAreaFilled(false);
        botao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao4ActionPerformed(evt);
            }
        });
        getContentPane().add(botao4);
        botao4.setBounds(20, 90, 120, 130);

        botao5.setFont(new java.awt.Font("Segoe UI", 3, 60)); // NOI18N
        botao5.setForeground(new java.awt.Color(255, 0, 0));
        botao5.setContentAreaFilled(false);
        botao5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao5ActionPerformed(evt);
            }
        });
        getContentPane().add(botao5);
        botao5.setBounds(150, 90, 160, 130);

        botao6.setFont(new java.awt.Font("Segoe UI", 3, 60)); // NOI18N
        botao6.setForeground(new java.awt.Color(255, 0, 0));
        botao6.setContentAreaFilled(false);
        botao6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao6ActionPerformed(evt);
            }
        });
        getContentPane().add(botao6);
        botao6.setBounds(330, 90, 120, 130);

        botao7.setFont(new java.awt.Font("Segoe UI", 3, 60)); // NOI18N
        botao7.setForeground(new java.awt.Color(255, 0, 0));
        botao7.setContentAreaFilled(false);
        botao7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao7ActionPerformed(evt);
            }
        });
        getContentPane().add(botao7);
        botao7.setBounds(20, 230, 120, 110);

        botao8.setFont(new java.awt.Font("Segoe UI", 3, 60)); // NOI18N
        botao8.setForeground(new java.awt.Color(255, 0, 0));
        botao8.setContentAreaFilled(false);
        botao8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao8ActionPerformed(evt);
            }
        });
        getContentPane().add(botao8);
        botao8.setBounds(151, 237, 160, 100);

        botao9.setFont(new java.awt.Font("Segoe UI", 3, 60)); // NOI18N
        botao9.setForeground(new java.awt.Color(255, 0, 0));
        botao9.setContentAreaFilled(false);
        botao9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao9ActionPerformed(evt);
            }
        });
        getContentPane().add(botao9);
        botao9.setBounds(330, 240, 120, 100);

        btnReiniciar.setText("NOVA RODADA");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnReiniciar);
        btnReiniciar.setBounds(20, 390, 168, 30);

        txtVisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVisorActionPerformed(evt);
            }
        });
        getContentPane().add(txtVisor);
        txtVisor.setBounds(20, 353, 430, 30);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\dhion\\OneDrive\\Área de Trabalho\\Imagem3.png")); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 440, 330);

        jLabel2.setText("RODADA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 390, 60, 16);

        contador.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        contador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contadorActionPerformed(evt);
            }
        });
        getContentPane().add(contador);
        contador.setBounds(200, 410, 70, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void jogadorDaVez() {
        if (jogA && jogB) {
            this.op = 1;
            jogA = false;
            jogB = true;
            txtVisor.setText("Vez do jogador O");
        } else {
            if (jogA && !jogB) {
                this.op = 1;
                jogA = false;
                jogB = true;
                txtVisor.setText("Vez do jogador O");
            } else {
                this.op = 2;
                jogA = true;
                jogB = false;
                txtVisor.setText("Vez do jogador X");
            }

        }

    }

    public void reiniciar() {
        for (i = 0; i < 3; i++) {
            for (j = 0; j < 3; j++) {
                posVetor[i][j] = "";

            }
        if(rodada == 5){
        rodada = 0;
        }

        }
        
    }

    public void vencedor() {
        linha1 = posVetor[0][0] + posVetor[0][1] + posVetor[0][2];
        linha2 = posVetor[1][0] + posVetor[1][1] + posVetor[1][2];
        linha3 = posVetor[2][0] + posVetor[2][1] + posVetor[2][2];
        coluna1 = posVetor[0][0] + posVetor[1][0] + posVetor[2][0];
        coluna2 = posVetor[0][1] + posVetor[1][1] + posVetor[2][1];
        coluna3 = posVetor[0][2] + posVetor[1][2] + posVetor[2][2];
        diagonal01 = posVetor[0][0] + posVetor[1][1] + posVetor[2][2];
        diagonal02 = posVetor[0][2] + posVetor[1][1] + posVetor[2][0];
        
        if (linha1.equals("XXX")) {
            txtVisor.setText("O vencedor é o X");
        this.botao1.setContentAreaFilled(true);
        this.botao1.setBackground(Color.GREEN);
        this.botao2.setContentAreaFilled(true);
        this.botao2.setBackground(Color.GREEN);
        this.botao3.setContentAreaFilled(true);
        this.botao3.setBackground(Color.GREEN);
        
        this.botao1.setEnabled(false);
        this.botao2.setEnabled(false);
        this.botao3.setEnabled(false);
        this.botao4.setEnabled(false);
        this.botao5.setEnabled(false);
        this.botao6.setEnabled(false);
        this.botao7.setEnabled(false);
        this.botao8.setEnabled(false);
        this.botao9.setEnabled(false);
        
        novaRodada = false;
        btnReiniciar.setEnabled(true);
        empate = true;
        resultadoX = 5;
        
        

        }
        else if (linha2.equals("XXX")) {
        txtVisor.setText("O vencedor é o X");
        this.botao3.setContentAreaFilled(true);
        this.botao3.setBackground(Color.GREEN);
        this.botao4.setContentAreaFilled(true);
        this.botao4.setBackground(Color.GREEN);
        this.botao5.setContentAreaFilled(true);
        this.botao5.setBackground(Color.GREEN);
        
        this.botao1.setEnabled(false);
        this.botao2.setEnabled(false);
        this.botao3.setEnabled(false);
        this.botao4.setEnabled(false);
        this.botao5.setEnabled(false);
        this.botao6.setEnabled(false);
        this.botao7.setEnabled(false);
        this.botao8.setEnabled(false);
        this.botao9.setEnabled(false);
        novaRodada = false;
         btnReiniciar.setEnabled(true);
         empate = true;
         resultadoX = 5;
        
         
        }
        else if (linha3.equals("XXX")) {
            
        txtVisor.setText("O vencedor é o X");
            
        this.botao7.setContentAreaFilled(true);
        this.botao7.setBackground(Color.GREEN);
        this.botao8.setContentAreaFilled(true);
        this.botao8.setBackground(Color.GREEN);
        this.botao9.setContentAreaFilled(true);
        this.botao9.setBackground(Color.GREEN);
            
            
        this.botao1.setEnabled(false);
        this.botao2.setEnabled(false);
        this.botao3.setEnabled(false);
        this.botao4.setEnabled(false);
        this.botao5.setEnabled(false);
        this.botao6.setEnabled(false);
        this.botao7.setEnabled(false);
        this.botao8.setEnabled(false);
        this.botao9.setEnabled(false);
        
        novaRodada = false;
         btnReiniciar.setEnabled(true);
         empate = true;
         resultadoX = 5;
         
         

        }
        else if (linha1.equals("OOO")) {
            txtVisor.setText("O vencedor é o O");
            this.botao1.setContentAreaFilled(true);
        this.botao1.setBackground(Color.GREEN);
        this.botao2.setContentAreaFilled(true);
        this.botao2.setBackground(Color.GREEN);
        this.botao3.setContentAreaFilled(true);
        this.botao3.setBackground(Color.GREEN);
        
            this.botao1.setEnabled(false);
        this.botao2.setEnabled(false);
        this.botao3.setEnabled(false);
        this.botao4.setEnabled(false);
        this.botao5.setEnabled(false);
        this.botao6.setEnabled(false);
        this.botao7.setEnabled(false);
        this.botao8.setEnabled(false);
        this.botao9.setEnabled(false);
        
        novaRodada = false;
         btnReiniciar.setEnabled(true);
         empate = true;
         resultadoy = 5;
         
         

        }
        else if (linha2.equals("OOO")) {
            txtVisor.setText("O vencedor é o O");
        this.botao6.setContentAreaFilled(true);
        this.botao6.setBackground(Color.GREEN);
        this.botao4.setContentAreaFilled(true);
        this.botao4.setBackground(Color.GREEN);
        this.botao5.setContentAreaFilled(true);
        this.botao5.setBackground(Color.GREEN);
            
        this.botao1.setEnabled(false);
        this.botao2.setEnabled(false);
        this.botao3.setEnabled(false);
        this.botao4.setEnabled(false);
        this.botao5.setEnabled(false);
        this.botao6.setEnabled(false);
        this.botao7.setEnabled(false);
        this.botao8.setEnabled(false);
        this.botao9.setEnabled(false);
        
        novaRodada = false;
         btnReiniciar.setEnabled(true);
         empate = true;
         resultadoy = 5;
           

        }
        else if (linha3.equals("OOO")) {
        txtVisor.setText("O vencedor é o O");
        
        this.botao7.setContentAreaFilled(true);
        this.botao7.setBackground(Color.GREEN);
        this.botao8.setContentAreaFilled(true);
        this.botao8.setBackground(Color.GREEN);
        this.botao9.setContentAreaFilled(true);
        this.botao9.setBackground(Color.GREEN);
        
        
        this.botao1.setEnabled(false);
        this.botao2.setEnabled(false);
        this.botao3.setEnabled(false);
        this.botao4.setEnabled(false);
        this.botao5.setEnabled(false);
        this.botao6.setEnabled(false);
        this.botao7.setEnabled(false);
        this.botao8.setEnabled(false);
        this.botao9.setEnabled(false);
        
        novaRodada = false;
         btnReiniciar.setEnabled(true);
         empate = true;
         resultadoy = 5;
         
        }
        else if (coluna1.equals("XXX")) {
        txtVisor.setText("O vencedor é o X");
        
        this.botao1.setContentAreaFilled(true);
        this.botao1.setBackground(Color.GREEN);
        this.botao4.setContentAreaFilled(true);
        this.botao4.setBackground(Color.GREEN);
        this.botao7.setContentAreaFilled(true);
        this.botao7.setBackground(Color.GREEN);
        
        
        
        this.botao1.setEnabled(false);
        this.botao2.setEnabled(false);
        this.botao3.setEnabled(false);
        this.botao4.setEnabled(false);
        this.botao5.setEnabled(false);
        this.botao6.setEnabled(false);
        this.botao7.setEnabled(false);
        this.botao8.setEnabled(false);
        this.botao9.setEnabled(false);
        
        novaRodada = false;
         btnReiniciar.setEnabled(true);
         empate = true;
        

        }
        else if (coluna2.equals("XXX")) {
        txtVisor.setText("O vencedor é o X");
        
        this.botao2.setContentAreaFilled(true);
        this.botao2.setBackground(Color.GREEN);
        this.botao5.setContentAreaFilled(true);
        this.botao5.setBackground(Color.GREEN);
        this.botao8.setContentAreaFilled(true);
        this.botao8.setBackground(Color.GREEN);
        
        
        this.botao1.setEnabled(false);
        this.botao2.setEnabled(false);
        this.botao3.setEnabled(false);
        this.botao4.setEnabled(false);
        this.botao5.setEnabled(false);
        this.botao6.setEnabled(false);
        this.botao7.setEnabled(false);
        this.botao8.setEnabled(false);
        this.botao9.setEnabled(false);
        
        novaRodada = false;
         btnReiniciar.setEnabled(true);
         empate = true;
         

        }
        else if (coluna3.equals("XXX")) {
        txtVisor.setText("O vencedor é o X");
        
        this.botao3.setContentAreaFilled(true);
        this.botao3.setBackground(Color.GREEN);
        this.botao6.setContentAreaFilled(true);
        this.botao6.setBackground(Color.GREEN);
        this.botao9.setContentAreaFilled(true);
        this.botao9.setBackground(Color.GREEN);
        
        
        this.botao1.setEnabled(false);
        this.botao2.setEnabled(false);
        this.botao3.setEnabled(false);
        this.botao4.setEnabled(false);
        this.botao5.setEnabled(false);
        this.botao6.setEnabled(false);
        this.botao7.setEnabled(false);
        this.botao8.setEnabled(false);
        this.botao9.setEnabled(false);
        
        novaRodada = false;
         btnReiniciar.setEnabled(true);
         empate = true;
         

        }
        else if (coluna1.equals("OOO")) {
        this.botao1.setContentAreaFilled(true);
        this.botao1.setBackground(Color.GREEN);
        this.botao4.setContentAreaFilled(true);
        this.botao4.setBackground(Color.GREEN);
        this.botao7.setContentAreaFilled(true);
        this.botao7.setBackground(Color.GREEN);    
        
        txtVisor.setText("O vencedor é o O");
        this.botao1.setEnabled(false);
        this.botao2.setEnabled(false);
        this.botao3.setEnabled(false);
        this.botao4.setEnabled(false);
        this.botao5.setEnabled(false);
        this.botao6.setEnabled(false);
        this.botao7.setEnabled(false);
        this.botao8.setEnabled(false);
        this.botao9.setEnabled(false);
        
        novaRodada = false;
         btnReiniciar.setEnabled(true);
         empate = true;
         

        }
        else if (coluna2.equals("OOO")) {
        txtVisor.setText("O vencedor é o O");
        
        this.botao2.setContentAreaFilled(true);
        this.botao2.setBackground(Color.GREEN);
        this.botao5.setContentAreaFilled(true);
        this.botao5.setBackground(Color.GREEN);
        this.botao8.setContentAreaFilled(true);
        this.botao8.setBackground(Color.GREEN);
        
        
        this.botao1.setEnabled(false);
        this.botao2.setEnabled(false);
        this.botao3.setEnabled(false);
        this.botao4.setEnabled(false);
        this.botao5.setEnabled(false);
        this.botao6.setEnabled(false);
        this.botao7.setEnabled(false);
        this.botao8.setEnabled(false);
        this.botao9.setEnabled(false);
        
        novaRodada = false;
         btnReiniciar.setEnabled(true);
         empate = true;
           

        }
        else if (coluna3.equals("OOO")) {
        txtVisor.setText("O vencedor é o O");
        
        this.botao3.setContentAreaFilled(true);
        this.botao3.setBackground(Color.GREEN);
        this.botao6.setContentAreaFilled(true);
        this.botao6.setBackground(Color.GREEN);
        this.botao9.setContentAreaFilled(true);
        this.botao9.setBackground(Color.GREEN);
            
              
        this.botao1.setEnabled(false);
        this.botao2.setEnabled(false);
        this.botao3.setEnabled(false);
        this.botao4.setEnabled(false);
        this.botao5.setEnabled(false);
        this.botao6.setEnabled(false);
        this.botao7.setEnabled(false);
        this.botao8.setEnabled(false);
        this.botao9.setEnabled(false);
        
        novaRodada = false;
         btnReiniciar.setEnabled(true);
         empate = true;
          

        }
        else if (diagonal01.equals("XXX")) {
        txtVisor.setText("O vencedor é o X");
        
        this.botao1.setContentAreaFilled(true);
        this.botao1.setBackground(Color.GREEN);
        this.botao5.setContentAreaFilled(true);
        this.botao5.setBackground(Color.GREEN);
        this.botao9.setContentAreaFilled(true);
        this.botao9.setBackground(Color.GREEN);
        
        this.botao1.setEnabled(false);
        this.botao2.setEnabled(false);
        this.botao3.setEnabled(false);
        this.botao4.setEnabled(false);
        this.botao5.setEnabled(false);
        this.botao6.setEnabled(false);
        this.botao7.setEnabled(false);
        this.botao8.setEnabled(false);
        this.botao9.setEnabled(false);
        
        novaRodada = false;
         btnReiniciar.setEnabled(true);
         empate = true;
           

        }
         
        else if (diagonal01.equals("OOO")) {
        txtVisor.setText("O vencedor é o O");
        
        this.botao1.setContentAreaFilled(true);
        this.botao1.setBackground(Color.GREEN);
        this.botao5.setContentAreaFilled(true);
        this.botao5.setBackground(Color.GREEN);
        this.botao9.setContentAreaFilled(true);
        this.botao9.setBackground(Color.GREEN);
        
        this.botao1.setEnabled(false);
        this.botao2.setEnabled(false);
        this.botao3.setEnabled(false);
        this.botao4.setEnabled(false);
        this.botao5.setEnabled(false);
        this.botao6.setEnabled(false);
        this.botao7.setEnabled(false);
        this.botao8.setEnabled(false);
        this.botao9.setEnabled(false);
        
        novaRodada = false;
         btnReiniciar.setEnabled(true);
         empate = true;
         

        }
        else if (diagonal02.equals("XXX")) {
        txtVisor.setText("O vencedor é o X");
        
        this.botao3.setContentAreaFilled(true);
        this.botao3.setBackground(Color.GREEN);
        this.botao5.setContentAreaFilled(true);
        this.botao5.setBackground(Color.GREEN);
        this.botao7.setContentAreaFilled(true);
        this.botao7.setBackground(Color.GREEN);
        
        this.botao1.setEnabled(false);
        this.botao2.setEnabled(false);
        this.botao3.setEnabled(false);
        this.botao4.setEnabled(false);
        this.botao5.setEnabled(false);
        this.botao6.setEnabled(false);
        this.botao7.setEnabled(false);
        this.botao8.setEnabled(false);
        this.botao9.setEnabled(false);
        
        novaRodada = false;
         btnReiniciar.setEnabled(true);
        empate = true;
         
           

        }
         
        if (diagonal02.equals("OOO")) {
        txtVisor.setText("O vencedor é o O");
        
        this.botao3.setContentAreaFilled(true);
        this.botao3.setBackground(Color.GREEN);
        this.botao5.setContentAreaFilled(true);
        this.botao5.setBackground(Color.GREEN);
        this.botao7.setContentAreaFilled(true);
        this.botao7.setBackground(Color.GREEN);
        
        this.botao1.setEnabled(false);
        this.botao2.setEnabled(false);
        this.botao3.setEnabled(false);
        this.botao4.setEnabled(false);
        this.botao5.setEnabled(false);
        this.botao6.setEnabled(false);
        this.botao7.setEnabled(false);
        this.botao8.setEnabled(false);
        this.botao9.setEnabled(false);
        
        novaRodada = false;
        btnReiniciar.setEnabled(true);
         
         empate = true;
           
         
        }
    if( contClic == 9 && novaRodada){
         txtVisor.setText("EMPATE");
    this.botao1.setContentAreaFilled(true);
    this.botao1.setBackground(Color.RED);
     this.botao2.setContentAreaFilled(true);
    this.botao2.setBackground(Color.RED);
     this.botao3.setContentAreaFilled(true);
    this.botao3.setBackground(Color.RED);
     this.botao4.setContentAreaFilled(true);
    this.botao4.setBackground(Color.RED);
     this.botao5.setContentAreaFilled(true);
    this.botao5.setBackground(Color.RED);
     this.botao6.setContentAreaFilled(true);
    this.botao6.setBackground(Color.RED);
     this.botao7.setContentAreaFilled(true);
    this.botao7.setBackground(Color.RED);
     this.botao8.setContentAreaFilled(true);
    this.botao8.setBackground(Color.RED);
    this.botao9.setContentAreaFilled(true);
    this.botao9.setBackground(Color.RED);
    JOptionPane.showMessageDialog(null, "EMAPATE");
    
     novaRodada = false;
        btnReiniciar.setEnabled(true);
    
    }
    
  
    
    
    
    
    }
       
    private void botao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao1ActionPerformed
        // TODO add your handling code here:
        jogadorDaVez();
        if (this.op == 1) {
            botao1.setText("X");
            posVetor[0][0] = "X";
            
        } else {
            botao1.setText("O");
            posVetor[0][0] = "O";
        }
        contClic = contClic + 1 ;
        
            
              
        botao1.setEnabled(false);
        vencedor();
    }//GEN-LAST:event_botao1ActionPerformed

    private void botao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao2ActionPerformed
        jogadorDaVez();
        if (this.op == 1) {
            botao2.setText("X");
            posVetor[0][1] = "X";
        } else {
            botao2.setText("O");
            posVetor[0][1] = "O";
        }
        
         contClic = contClic + 1 ;
        botao2.setEnabled(false);
        vencedor();// TODO add your handling code here:
    }//GEN-LAST:event_botao2ActionPerformed

    private void botao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao3ActionPerformed
            jogadorDaVez();
        if (this.op == 1) {
            botao3.setText("X");
            posVetor[0][2] = "X";
        } else {
            botao3.setText("O");
            posVetor[0][2] = "O";
        }
        
         contClic = contClic + 1 ;
        botao3.setEnabled(false);
        vencedor();
    }//GEN-LAST:event_botao3ActionPerformed

    private void botao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao4ActionPerformed
            jogadorDaVez();
        if (this.op == 1) {
            botao4.setText("X");
            posVetor[1][0] = "X";
        } else {
            botao4.setText("O");
            posVetor[1][0] = "O";
        }
       
         contClic = contClic + 1 ;
        botao4.setEnabled(false);
        vencedor();
    }//GEN-LAST:event_botao4ActionPerformed

    private void botao5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao5ActionPerformed
            jogadorDaVez();
        if (this.op == 1) {
            botao5.setText("X");
            posVetor[1][1] = "X";
        } else {
            botao5.setText("O");
            posVetor[1][1] = "O";
        }
         contClic = contClic + 1 ;
        
        botao5.setEnabled(false);
        vencedor();
    }//GEN-LAST:event_botao5ActionPerformed

    private void botao6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao6ActionPerformed
            jogadorDaVez();
        if (this.op == 1) {
            botao6.setText("X");
            posVetor[1][2] = "X";
        } else {
            botao6.setText("O");
            posVetor[1][2] = "O";
        }
         contClic = contClic + 1 ;
        
        botao6.setEnabled(false);
        vencedor();
    }//GEN-LAST:event_botao6ActionPerformed

    private void botao8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao8ActionPerformed
            jogadorDaVez();
        if (this.op == 1) {
            botao8.setText("X");
            posVetor[2][1] = "X";
        } else {
            botao8.setText("O");
            posVetor[2][1] = "O";
        }
         contClic = contClic + 1 ;
        botao8.setEnabled(false);
        vencedor();
    }//GEN-LAST:event_botao8ActionPerformed

    private void botao9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao9ActionPerformed
           jogadorDaVez();
        if (this.op == 1) {
            botao9.setText("X");
            posVetor[2][2] = "X";
        } else {
            botao9.setText("O");
            posVetor[2][2] = "O";
        }
        
         contClic = contClic + 1 ;
        botao9.setEnabled(false);
        vencedor();
    }//GEN-LAST:event_botao9ActionPerformed

    private void botao7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao7ActionPerformed
            jogadorDaVez();
        if (this.op == 1) {
            botao7.setText("X");
            posVetor[2][0] = "X";
        } else {
            botao7.setText("O");
            posVetor[2][0] = "O";
        }
         contClic = contClic + 1 ;
        
        botao7.setEnabled(false);
        vencedor();
    }//GEN-LAST:event_botao7ActionPerformed

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
       
        if(!novaRodada){
        btnReiniciar.setEnabled(false);
        novaRodada = true;
        this.botao1.setText("");
        this.botao2.setText("");
        this.botao3.setText("");
        this.botao4.setText("");
        this.botao5.setText("");
        this.botao6.setText("");
        this.botao7.setText("");
        this.botao8.setText("");
        this.botao9.setText("");
        this.botao1.setEnabled(true);
        this.botao2.setEnabled(true);
        this.botao3.setEnabled(true);
        this.botao4.setEnabled(true);
        this.botao5.setEnabled(true);
        this.botao6.setEnabled(true);
        this.botao7.setEnabled(true);
        this.botao8.setEnabled(true);
        this.botao9.setEnabled(true);
        this.botao1.setContentAreaFilled(false);
        this.botao2.setContentAreaFilled(false);
        this.botao3.setContentAreaFilled(false);
        this.botao4.setContentAreaFilled(false);
        this.botao5.setContentAreaFilled(false);
        this.botao6.setContentAreaFilled(false);
        this.botao7.setContentAreaFilled(false);
        this.botao8.setContentAreaFilled(false);
        this.botao9.setContentAreaFilled(false);
        rodada = rodada + 1;
        contador.setText(Integer.toString(rodada));
        
        txtVisor.setText("");
        jogA = true;
        jogB = true;  
        empate = false;
        contClic = 0;
        reiniciar();}
        contador.setEnabled(false);
    }//GEN-LAST:event_btnReiniciarActionPerformed

    private void txtVisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVisorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVisorActionPerformed

    private void contadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contadorActionPerformed
        
        
    }//GEN-LAST:event_contadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao1;
    private javax.swing.JButton botao2;
    private javax.swing.JButton botao3;
    private javax.swing.JButton botao4;
    private javax.swing.JButton botao5;
    private javax.swing.JButton botao6;
    private javax.swing.JButton botao7;
    private javax.swing.JButton botao8;
    private javax.swing.JButton botao9;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JTextField contador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtVisor;
    // End of variables declaration//GEN-END:variables
}
